// Code generated by go-swagger; DO NOT EDIT.

package admin

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/ory/hydra/internal/httpclient/models"
)

// ExpireConsentSessionsReader is a Reader for the ExpireConsentSessions structure.
type ExpireConsentSessionsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *ExpireConsentSessionsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewExpireConsentSessionsNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewExpireConsentSessionsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewExpireConsentSessionsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewExpireConsentSessionsNoContent creates a ExpireConsentSessionsNoContent with default headers values
func NewExpireConsentSessionsNoContent() *ExpireConsentSessionsNoContent {
	return &ExpireConsentSessionsNoContent{}
}

/* ExpireConsentSessionsNoContent describes a response with status code 204, with default header values.

 Empty responses are sent when, for example, resources are deleted. The HTTP status code for empty responses is
typically 201.
*/
type ExpireConsentSessionsNoContent struct {
}

func (o *ExpireConsentSessionsNoContent) Error() string {
	return fmt.Sprintf("[PUT /oauth2/auth/sessions/consent][%d] expireConsentSessionsNoContent ", 204)
}

func (o *ExpireConsentSessionsNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewExpireConsentSessionsBadRequest creates a ExpireConsentSessionsBadRequest with default headers values
func NewExpireConsentSessionsBadRequest() *ExpireConsentSessionsBadRequest {
	return &ExpireConsentSessionsBadRequest{}
}

/* ExpireConsentSessionsBadRequest describes a response with status code 400, with default header values.

jsonError
*/
type ExpireConsentSessionsBadRequest struct {
	Payload *models.JSONError
}

func (o *ExpireConsentSessionsBadRequest) Error() string {
	return fmt.Sprintf("[PUT /oauth2/auth/sessions/consent][%d] expireConsentSessionsBadRequest  %+v", 400, o.Payload)
}
func (o *ExpireConsentSessionsBadRequest) GetPayload() *models.JSONError {
	return o.Payload
}

func (o *ExpireConsentSessionsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.JSONError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewExpireConsentSessionsInternalServerError creates a ExpireConsentSessionsInternalServerError with default headers values
func NewExpireConsentSessionsInternalServerError() *ExpireConsentSessionsInternalServerError {
	return &ExpireConsentSessionsInternalServerError{}
}

/* ExpireConsentSessionsInternalServerError describes a response with status code 500, with default header values.

jsonError
*/
type ExpireConsentSessionsInternalServerError struct {
	Payload *models.JSONError
}

func (o *ExpireConsentSessionsInternalServerError) Error() string {
	return fmt.Sprintf("[PUT /oauth2/auth/sessions/consent][%d] expireConsentSessionsInternalServerError  %+v", 500, o.Payload)
}
func (o *ExpireConsentSessionsInternalServerError) GetPayload() *models.JSONError {
	return o.Payload
}

func (o *ExpireConsentSessionsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.JSONError)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
