// Code generated by go-swagger; DO NOT EDIT.

package admin

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewExpireConsentSessionsParams creates a new ExpireConsentSessionsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewExpireConsentSessionsParams() *ExpireConsentSessionsParams {
	return &ExpireConsentSessionsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewExpireConsentSessionsParamsWithTimeout creates a new ExpireConsentSessionsParams object
// with the ability to set a timeout on a request.
func NewExpireConsentSessionsParamsWithTimeout(timeout time.Duration) *ExpireConsentSessionsParams {
	return &ExpireConsentSessionsParams{
		timeout: timeout,
	}
}

// NewExpireConsentSessionsParamsWithContext creates a new ExpireConsentSessionsParams object
// with the ability to set a context for a request.
func NewExpireConsentSessionsParamsWithContext(ctx context.Context) *ExpireConsentSessionsParams {
	return &ExpireConsentSessionsParams{
		Context: ctx,
	}
}

// NewExpireConsentSessionsParamsWithHTTPClient creates a new ExpireConsentSessionsParams object
// with the ability to set a custom HTTPClient for a request.
func NewExpireConsentSessionsParamsWithHTTPClient(client *http.Client) *ExpireConsentSessionsParams {
	return &ExpireConsentSessionsParams{
		HTTPClient: client,
	}
}

/* ExpireConsentSessionsParams contains all the parameters to send to the API endpoint
   for the expire consent sessions operation.

   Typically these are written to a http.Request.
*/
type ExpireConsentSessionsParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the expire consent sessions params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ExpireConsentSessionsParams) WithDefaults() *ExpireConsentSessionsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the expire consent sessions params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ExpireConsentSessionsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the expire consent sessions params
func (o *ExpireConsentSessionsParams) WithTimeout(timeout time.Duration) *ExpireConsentSessionsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the expire consent sessions params
func (o *ExpireConsentSessionsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the expire consent sessions params
func (o *ExpireConsentSessionsParams) WithContext(ctx context.Context) *ExpireConsentSessionsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the expire consent sessions params
func (o *ExpireConsentSessionsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the expire consent sessions params
func (o *ExpireConsentSessionsParams) WithHTTPClient(client *http.Client) *ExpireConsentSessionsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the expire consent sessions params
func (o *ExpireConsentSessionsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *ExpireConsentSessionsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
