// Code generated by go-swagger; DO NOT EDIT.

package admin

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewListSubjectConsentSessionsParams creates a new ListSubjectConsentSessionsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewListSubjectConsentSessionsParams() *ListSubjectConsentSessionsParams {
	return &ListSubjectConsentSessionsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewListSubjectConsentSessionsParamsWithTimeout creates a new ListSubjectConsentSessionsParams object
// with the ability to set a timeout on a request.
func NewListSubjectConsentSessionsParamsWithTimeout(timeout time.Duration) *ListSubjectConsentSessionsParams {
	return &ListSubjectConsentSessionsParams{
		timeout: timeout,
	}
}

// NewListSubjectConsentSessionsParamsWithContext creates a new ListSubjectConsentSessionsParams object
// with the ability to set a context for a request.
func NewListSubjectConsentSessionsParamsWithContext(ctx context.Context) *ListSubjectConsentSessionsParams {
	return &ListSubjectConsentSessionsParams{
		Context: ctx,
	}
}

// NewListSubjectConsentSessionsParamsWithHTTPClient creates a new ListSubjectConsentSessionsParams object
// with the ability to set a custom HTTPClient for a request.
func NewListSubjectConsentSessionsParamsWithHTTPClient(client *http.Client) *ListSubjectConsentSessionsParams {
	return &ListSubjectConsentSessionsParams{
		HTTPClient: client,
	}
}

/* ListSubjectConsentSessionsParams contains all the parameters to send to the API endpoint
   for the list subject consent sessions operation.

   Typically these are written to a http.Request.
*/
type ListSubjectConsentSessionsParams struct {

	/* IncludeExpired.

	   Option to return partially or fully expired consent sessions. Partially expired consent sessions are consent sessions, where at least one consent session in login session is still active. In this case all consent sessions from such login session are returned.
	*/
	IncludeExpired *string

	/* Limit.

	   The maximum amount of consent sessions to be returned, upper bound is 500 sessions.

	   Format: int64
	*/
	Limit *int64

	/* LoginSessionID.

	   The login session id to list the consent sessions for.
	*/
	LoginSessionID *string

	/* Offset.

	   The offset from where to start looking.

	   Format: int64
	*/
	Offset *int64

	// Subject.
	Subject string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the list subject consent sessions params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListSubjectConsentSessionsParams) WithDefaults() *ListSubjectConsentSessionsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the list subject consent sessions params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ListSubjectConsentSessionsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the list subject consent sessions params
func (o *ListSubjectConsentSessionsParams) WithTimeout(timeout time.Duration) *ListSubjectConsentSessionsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the list subject consent sessions params
func (o *ListSubjectConsentSessionsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the list subject consent sessions params
func (o *ListSubjectConsentSessionsParams) WithContext(ctx context.Context) *ListSubjectConsentSessionsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the list subject consent sessions params
func (o *ListSubjectConsentSessionsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the list subject consent sessions params
func (o *ListSubjectConsentSessionsParams) WithHTTPClient(client *http.Client) *ListSubjectConsentSessionsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the list subject consent sessions params
func (o *ListSubjectConsentSessionsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithIncludeExpired adds the includeExpired to the list subject consent sessions params
func (o *ListSubjectConsentSessionsParams) WithIncludeExpired(includeExpired *string) *ListSubjectConsentSessionsParams {
	o.SetIncludeExpired(includeExpired)
	return o
}

// SetIncludeExpired adds the includeExpired to the list subject consent sessions params
func (o *ListSubjectConsentSessionsParams) SetIncludeExpired(includeExpired *string) {
	o.IncludeExpired = includeExpired
}

// WithLimit adds the limit to the list subject consent sessions params
func (o *ListSubjectConsentSessionsParams) WithLimit(limit *int64) *ListSubjectConsentSessionsParams {
	o.SetLimit(limit)
	return o
}

// SetLimit adds the limit to the list subject consent sessions params
func (o *ListSubjectConsentSessionsParams) SetLimit(limit *int64) {
	o.Limit = limit
}

// WithLoginSessionID adds the loginSessionID to the list subject consent sessions params
func (o *ListSubjectConsentSessionsParams) WithLoginSessionID(loginSessionID *string) *ListSubjectConsentSessionsParams {
	o.SetLoginSessionID(loginSessionID)
	return o
}

// SetLoginSessionID adds the loginSessionId to the list subject consent sessions params
func (o *ListSubjectConsentSessionsParams) SetLoginSessionID(loginSessionID *string) {
	o.LoginSessionID = loginSessionID
}

// WithOffset adds the offset to the list subject consent sessions params
func (o *ListSubjectConsentSessionsParams) WithOffset(offset *int64) *ListSubjectConsentSessionsParams {
	o.SetOffset(offset)
	return o
}

// SetOffset adds the offset to the list subject consent sessions params
func (o *ListSubjectConsentSessionsParams) SetOffset(offset *int64) {
	o.Offset = offset
}

// WithSubject adds the subject to the list subject consent sessions params
func (o *ListSubjectConsentSessionsParams) WithSubject(subject string) *ListSubjectConsentSessionsParams {
	o.SetSubject(subject)
	return o
}

// SetSubject adds the subject to the list subject consent sessions params
func (o *ListSubjectConsentSessionsParams) SetSubject(subject string) {
	o.Subject = subject
}

// WriteToRequest writes these params to a swagger request
func (o *ListSubjectConsentSessionsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.IncludeExpired != nil {

		// query param include_expired
		var qrIncludeExpired string

		if o.IncludeExpired != nil {
			qrIncludeExpired = *o.IncludeExpired
		}
		qIncludeExpired := qrIncludeExpired
		if qIncludeExpired != "" {

			if err := r.SetQueryParam("include_expired", qIncludeExpired); err != nil {
				return err
			}
		}
	}

	if o.Limit != nil {

		// query param limit
		var qrLimit int64

		if o.Limit != nil {
			qrLimit = *o.Limit
		}
		qLimit := swag.FormatInt64(qrLimit)
		if qLimit != "" {

			if err := r.SetQueryParam("limit", qLimit); err != nil {
				return err
			}
		}
	}

	if o.LoginSessionID != nil {

		// query param login_session_id
		var qrLoginSessionID string

		if o.LoginSessionID != nil {
			qrLoginSessionID = *o.LoginSessionID
		}
		qLoginSessionID := qrLoginSessionID
		if qLoginSessionID != "" {

			if err := r.SetQueryParam("login_session_id", qLoginSessionID); err != nil {
				return err
			}
		}
	}

	if o.Offset != nil {

		// query param offset
		var qrOffset int64

		if o.Offset != nil {
			qrOffset = *o.Offset
		}
		qOffset := swag.FormatInt64(qrOffset)
		if qOffset != "" {

			if err := r.SetQueryParam("offset", qOffset); err != nil {
				return err
			}
		}
	}

	// query param subject
	qrSubject := o.Subject
	qSubject := qrSubject
	if qSubject != "" {

		if err := r.SetQueryParam("subject", qSubject); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
