-- Migration generated by the command below; DO NOT EDIT.
-- hydra:generate hydra migrate gen
DELETE FROM hydra_oauth2_logout_request WHERE redir_url IS NULL;
ALTER TABLE hydra_oauth2_logout_request ALTER COLUMN redir_url SET NOT NULL;
