// Copyright © 2022 Ory Corp
// SPDX-License-Identifier: Apache-2.0

//go:build hsm
// +build hsm

// Code generated by MockGen. DO NOT EDIT.
// Source: hsm/hsm.go

// Package hsm_test is a generated GoMock package.
package hsm_test

import (
	reflect "reflect"

	crypto11 "github.com/ThalesIgnite/crypto11"
	gomock "github.com/golang/mock/gomock"
)

// MockContext is a mock of Context interface.
type MockContext struct {
	ctrl     *gomock.Controller
	recorder *MockContextMockRecorder
}

// MockContextMockRecorder is the mock recorder for MockContext.
type MockContextMockRecorder struct {
	mock *MockContext
}

// NewMockContext creates a new mock instance.
func NewMockContext(ctrl *gomock.Controller) *MockContext {
	mock := &MockContext{ctrl: ctrl}
	mock.recorder = &MockContextMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockContext) EXPECT() *MockContextMockRecorder {
	return m.recorder
}

// FindKeyPair mocks base method.
func (m *MockContext) FindKeyPair(id, label []byte) (crypto11.Signer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindKeyPair", id, label)
	ret0, _ := ret[0].(crypto11.Signer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindKeyPair indicates an expected call of FindKeyPair.
func (mr *MockContextMockRecorder) FindKeyPair(id, label interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindKeyPair", reflect.TypeOf((*MockContext)(nil).FindKeyPair), id, label)
}

// FindKeyPairs mocks base method.
func (m *MockContext) FindKeyPairs(id, label []byte) ([]crypto11.Signer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindKeyPairs", id, label)
	ret0, _ := ret[0].([]crypto11.Signer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindKeyPairs indicates an expected call of FindKeyPairs.
func (mr *MockContextMockRecorder) FindKeyPairs(id, label interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindKeyPairs", reflect.TypeOf((*MockContext)(nil).FindKeyPairs), id, label)
}

// GetAttribute mocks base method.
func (m *MockContext) GetAttribute(key interface{}, attribute crypto11.AttributeType) (*crypto11.Attribute, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAttribute", key, attribute)
	ret0, _ := ret[0].(*crypto11.Attribute)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAttribute indicates an expected call of GetAttribute.
func (mr *MockContextMockRecorder) GetAttribute(key, attribute interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAttribute", reflect.TypeOf((*MockContext)(nil).GetAttribute), key, attribute)
}

// Close mocks base method.
func (m *MockContext) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockContextMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockContext)(nil).Close))
}
