FROM golang:1.19-alpine3.17 AS builder

RUN apk -U --no-cache upgrade && apk --no-cache add build-base git gcc bash

WORKDIR /go/src/github.com/ory/hydra
RUN mkdir -p ./internal/httpclient

COPY go.mod go.sum ./
COPY internal/httpclient/go.* ./internal/httpclient

ENV GO111MODULE on
ENV CGO_ENABLED 1

RUN go mod download

COPY . .

FROM builder as build-hydra
RUN go build -tags sqlite,json1,hsm -o /usr/bin/hydra

FROM builder as test-hsm
ENV HSM_ENABLED=true
# Ory Hydra and hsm-generate-keys.sh load SoftHSM through OpenSC's pkcs11-spy, which logs all PKCS#11 calls to
# PKCS11SPY_OUTPUT. The end of the log is printed when tests fail.
ENV HSM_LIBRARY=/usr/lib/pkcs11-spy.so
ENV PKCS11SPY=/usr/lib/softhsm/libsofthsm2.so
ENV PKCS11SPY_OUTPUT=/tmp/pkcs11-spy.log
ENV HSM_TOKEN_LABEL=hydra
ENV HSM_PIN=1234

RUN apk --no-cache --upgrade --latest add softhsm opensc; \
    pkcs11-tool --module /usr/lib/softhsm/libsofthsm2.so --slot 0 --init-token --so-pin 0000 --init-pin --pin 1234 --label hydra; \
    ./scripts/hsm-generate-keys.sh; \
    go test -p 1 -v -failfast -short -tags=sqlite,hsm ./... || { tail -n 500 "$PKCS11SPY_OUTPUT"; exit 1; }

FROM alpine:3.15

COPY scripts/hsm-generate-keys.sh /usr/local/bin/hsm-generate-keys.sh

RUN apk --no-cache --upgrade --latest add softhsm opensc; \
    pkcs11-tool --module /usr/lib/softhsm/libsofthsm2.so --slot 0 --init-token --so-pin 0000 --init-pin --pin 1234 --label hydra; \
    hsm-generate-keys.sh

RUN addgroup -S ory; \
    adduser -S ory -G ory -D  -h /home/ory -s /bin/nologin; \
    chown -R ory:ory /home/ory; \
    chown -R ory:ory /var/lib/softhsm/tokens

COPY --from=build-hydra /usr/bin/hydra /usr/bin/hydra

# To log all PKCS#11 calls, set HSM_LIBRARY=/usr/lib/pkcs11-spy.so. OpenSC's pkcs11-spy then forwards the calls to
# PKCS11SPY and logs them to PKCS11SPY_OUTPUT.
ENV PKCS11SPY=/usr/lib/softhsm/libsofthsm2.so
ENV PKCS11SPY_OUTPUT=/home/ory/pkcs11-spy.log

# By creating the sqlite folder as the ory user, the mounted volume will be owned by ory:ory, which
# is required for read/write of SQLite.
RUN mkdir -p /var/lib/sqlite && \
    chown ory:ory /var/lib/sqlite

VOLUME /var/lib/sqlite

# Exposing the ory home directory
VOLUME /home/ory

# Declare the standard ports used by hydra (4444 for public service endpoint, 4445 for admin service endpoint)
EXPOSE 4444 4445

USER ory

ENTRYPOINT ["hydra"]
CMD ["serve"]
