/*
Ory Hydra API

Documentation for all of Ory Hydra's APIs.

API version:
Contact: hi@ory.sh
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// LoginSessionClaims Identity and authentication claims of a login session, taken from its most recently granted consent.
type LoginSessionClaims struct {
	// ACR is the Authentication Context Class Reference value of the login session.
	Acr *string `json:"acr,omitempty"`
	// AMR is the Authentication Methods References value of the login session.
	Amr []string `json:"amr,omitempty"`
	// AuthTime is the time (in seconds since the Unix epoch) when the end-user authenticated.
	AuthTime *int64 `json:"auth_time,omitempty"`
	// Birthdate is the birthdate claim set in the consent session's ID token data.
	Birthdate interface{} `json:"birthdate,omitempty"`
	// FamilyName is the family_name claim set in the consent session's ID token data.
	FamilyName interface{} `json:"family_name,omitempty"`
	// GivenName is the given_name claim set in the consent session's ID token data.
	GivenName interface{} `json:"given_name,omitempty"`
	// PhoneNumber is the phone_number claim set in the consent session's ID token data.
	PhoneNumber interface{} `json:"phone_number,omitempty"`
	// PhoneNumberVerified is the phone_number_verified claim set in the consent session's ID token data.
	PhoneNumberVerified interface{} `json:"phone_number_verified,omitempty"`
	// Subject is the subject of the login session.
	Subject *string `json:"subject,omitempty"`
}

// NewLoginSessionClaims instantiates a new LoginSessionClaims object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLoginSessionClaims() *LoginSessionClaims {
	this := LoginSessionClaims{}
	return &this
}

// NewLoginSessionClaimsWithDefaults instantiates a new LoginSessionClaims object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLoginSessionClaimsWithDefaults() *LoginSessionClaims {
	this := LoginSessionClaims{}
	return &this
}

// GetAcr returns the Acr field value if set, zero value otherwise.
func (o *LoginSessionClaims) GetAcr() string {
	if o == nil || o.Acr == nil {
		var ret string
		return ret
	}
	return *o.Acr
}

// GetAcrOk returns a tuple with the Acr field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LoginSessionClaims) GetAcrOk() (*string, bool) {
	if o == nil || o.Acr == nil {
		return nil, false
	}
	return o.Acr, true
}

// HasAcr returns a boolean if a field has been set.
func (o *LoginSessionClaims) HasAcr() bool {
	if o != nil && o.Acr != nil {
		return true
	}

	return false
}

// SetAcr gets a reference to the given string and assigns it to the Acr field.
func (o *LoginSessionClaims) SetAcr(v string) {
	o.Acr = &v
}

// GetAmr returns the Amr field value if set, zero value otherwise.
func (o *LoginSessionClaims) GetAmr() []string {
	if o == nil || o.Amr == nil {
		var ret []string
		return ret
	}
	return o.Amr
}

// GetAmrOk returns a tuple with the Amr field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LoginSessionClaims) GetAmrOk() ([]string, bool) {
	if o == nil || o.Amr == nil {
		return nil, false
	}
	return o.Amr, true
}

// HasAmr returns a boolean if a field has been set.
func (o *LoginSessionClaims) HasAmr() bool {
	if o != nil && o.Amr != nil {
		return true
	}

	return false
}

// SetAmr gets a reference to the given []string and assigns it to the Amr field.
func (o *LoginSessionClaims) SetAmr(v []string) {
	o.Amr = v
}

// GetAuthTime returns the AuthTime field value if set, zero value otherwise.
func (o *LoginSessionClaims) GetAuthTime() int64 {
	if o == nil || o.AuthTime == nil {
		var ret int64
		return ret
	}
	return *o.AuthTime
}

// GetAuthTimeOk returns a tuple with the AuthTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LoginSessionClaims) GetAuthTimeOk() (*int64, bool) {
	if o == nil || o.AuthTime == nil {
		return nil, false
	}
	return o.AuthTime, true
}

// HasAuthTime returns a boolean if a field has been set.
func (o *LoginSessionClaims) HasAuthTime() bool {
	if o != nil && o.AuthTime != nil {
		return true
	}

	return false
}

// SetAuthTime gets a reference to the given int64 and assigns it to the AuthTime field.
func (o *LoginSessionClaims) SetAuthTime(v int64) {
	o.AuthTime = &v
}

// GetBirthdate returns the Birthdate field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *LoginSessionClaims) GetBirthdate() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Birthdate
}

// GetBirthdateOk returns a tuple with the Birthdate field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *LoginSessionClaims) GetBirthdateOk() (*interface{}, bool) {
	if o == nil || o.Birthdate == nil {
		return nil, false
	}
	return &o.Birthdate, true
}

// HasBirthdate returns a boolean if a field has been set.
func (o *LoginSessionClaims) HasBirthdate() bool {
	if o != nil && o.Birthdate != nil {
		return true
	}

	return false
}

// SetBirthdate gets a reference to the given interface{} and assigns it to the Birthdate field.
func (o *LoginSessionClaims) SetBirthdate(v interface{}) {
	o.Birthdate = v
}

// GetFamilyName returns the FamilyName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *LoginSessionClaims) GetFamilyName() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.FamilyName
}

// GetFamilyNameOk returns a tuple with the FamilyName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *LoginSessionClaims) GetFamilyNameOk() (*interface{}, bool) {
	if o == nil || o.FamilyName == nil {
		return nil, false
	}
	return &o.FamilyName, true
}

// HasFamilyName returns a boolean if a field has been set.
func (o *LoginSessionClaims) HasFamilyName() bool {
	if o != nil && o.FamilyName != nil {
		return true
	}

	return false
}

// SetFamilyName gets a reference to the given interface{} and assigns it to the FamilyName field.
func (o *LoginSessionClaims) SetFamilyName(v interface{}) {
	o.FamilyName = v
}

// GetGivenName returns the GivenName field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *LoginSessionClaims) GetGivenName() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.GivenName
}

// GetGivenNameOk returns a tuple with the GivenName field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *LoginSessionClaims) GetGivenNameOk() (*interface{}, bool) {
	if o == nil || o.GivenName == nil {
		return nil, false
	}
	return &o.GivenName, true
}

// HasGivenName returns a boolean if a field has been set.
func (o *LoginSessionClaims) HasGivenName() bool {
	if o != nil && o.GivenName != nil {
		return true
	}

	return false
}

// SetGivenName gets a reference to the given interface{} and assigns it to the GivenName field.
func (o *LoginSessionClaims) SetGivenName(v interface{}) {
	o.GivenName = v
}

// GetPhoneNumber returns the PhoneNumber field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *LoginSessionClaims) GetPhoneNumber() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.PhoneNumber
}

// GetPhoneNumberOk returns a tuple with the PhoneNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *LoginSessionClaims) GetPhoneNumberOk() (*interface{}, bool) {
	if o == nil || o.PhoneNumber == nil {
		return nil, false
	}
	return &o.PhoneNumber, true
}

// HasPhoneNumber returns a boolean if a field has been set.
func (o *LoginSessionClaims) HasPhoneNumber() bool {
	if o != nil && o.PhoneNumber != nil {
		return true
	}

	return false
}

// SetPhoneNumber gets a reference to the given interface{} and assigns it to the PhoneNumber field.
func (o *LoginSessionClaims) SetPhoneNumber(v interface{}) {
	o.PhoneNumber = v
}

// GetPhoneNumberVerified returns the PhoneNumberVerified field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *LoginSessionClaims) GetPhoneNumberVerified() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.PhoneNumberVerified
}

// GetPhoneNumberVerifiedOk returns a tuple with the PhoneNumberVerified field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *LoginSessionClaims) GetPhoneNumberVerifiedOk() (*interface{}, bool) {
	if o == nil || o.PhoneNumberVerified == nil {
		return nil, false
	}
	return &o.PhoneNumberVerified, true
}

// HasPhoneNumberVerified returns a boolean if a field has been set.
func (o *LoginSessionClaims) HasPhoneNumberVerified() bool {
	if o != nil && o.PhoneNumberVerified != nil {
		return true
	}

	return false
}

// SetPhoneNumberVerified gets a reference to the given interface{} and assigns it to the PhoneNumberVerified field.
func (o *LoginSessionClaims) SetPhoneNumberVerified(v interface{}) {
	o.PhoneNumberVerified = v
}

// GetSubject returns the Subject field value if set, zero value otherwise.
func (o *LoginSessionClaims) GetSubject() string {
	if o == nil || o.Subject == nil {
		var ret string
		return ret
	}
	return *o.Subject
}

// GetSubjectOk returns a tuple with the Subject field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LoginSessionClaims) GetSubjectOk() (*string, bool) {
	if o == nil || o.Subject == nil {
		return nil, false
	}
	return o.Subject, true
}

// HasSubject returns a boolean if a field has been set.
func (o *LoginSessionClaims) HasSubject() bool {
	if o != nil && o.Subject != nil {
		return true
	}

	return false
}

// SetSubject gets a reference to the given string and assigns it to the Subject field.
func (o *LoginSessionClaims) SetSubject(v string) {
	o.Subject = &v
}

func (o LoginSessionClaims) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Acr != nil {
		toSerialize["acr"] = o.Acr
	}
	if o.Amr != nil {
		toSerialize["amr"] = o.Amr
	}
	if o.AuthTime != nil {
		toSerialize["auth_time"] = o.AuthTime
	}
	if o.Birthdate != nil {
		toSerialize["birthdate"] = o.Birthdate
	}
	if o.FamilyName != nil {
		toSerialize["family_name"] = o.FamilyName
	}
	if o.GivenName != nil {
		toSerialize["given_name"] = o.GivenName
	}
	if o.PhoneNumber != nil {
		toSerialize["phone_number"] = o.PhoneNumber
	}
	if o.PhoneNumberVerified != nil {
		toSerialize["phone_number_verified"] = o.PhoneNumberVerified
	}
	if o.Subject != nil {
		toSerialize["subject"] = o.Subject
	}
	return json.Marshal(toSerialize)
}

type NullableLoginSessionClaims struct {
	value *LoginSessionClaims
	isSet bool
}

func (v NullableLoginSessionClaims) Get() *LoginSessionClaims {
	return v.value
}

func (v *NullableLoginSessionClaims) Set(val *LoginSessionClaims) {
	v.value = val
	v.isSet = true
}

func (v NullableLoginSessionClaims) IsSet() bool {
	return v.isSet
}

func (v *NullableLoginSessionClaims) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLoginSessionClaims(val *LoginSessionClaims) *NullableLoginSessionClaims {
	return &NullableLoginSessionClaims{value: val, isSet: true}
}

func (v NullableLoginSessionClaims) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLoginSessionClaims) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
